Repository LaFavela/favela, pull requests merged in 2023-05, with the labels that each got.

#10 rating-system and merchant profile
  src/pages/login.tsx
  src/pages/merchantProfile.tsx
  src/pages/rating.tsx
Labels: enhancement

#11 updated module packages please run 'npm install'
  package-lock.json
  package.json
Labels: documentation

#15 Update .gitignore to add .env
  .gitignore
Labels: bug, documentation
