Repository LaFavela/favela, pull requests merged in 2023-06, with the labels that each got.

#16 Needed For Authentications and Apis, database is merged and various backend solutions
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20230523050948_init/migration.sql
  prisma/migrations/20230524060639_asd/migration.sql
  prisma/migrations/20230531105008_riil_data_base/migration.sql
  prisma/migrations/20230602181247_added/migration.sql
  prisma/migrations/20230604103205_added/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/components/Providers.tsx
  src/lib/prisma.ts
  src/pages/_document.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/login.ts
  src/pages/api/auth/signup.ts
  src/pages/api/auth/user.ts
  src/pages/api/design.ts
  src/pages/api/designer.ts
  src/pages/api/property.ts
  src/pages/api/tukang.ts
  src/pages/api/zhello.ts
  tsconfig.json
Labels: enhancement

#19 Removed Desktop.ini
  .gitignore
  public/assets/build/desktop.ini
Labels: good first issue

#21 Finished Session
  next.config.js
  package-lock.json
  package.json
  prisma/migrations/20230610092343_fixed_provinsiand_kota/migration.sql
  prisma/schema.prisma
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/login/route.ts
  src/app/api/register/route.ts
  src/components/login.tsx
  src/components/loginButton.tsx
  src/components/navbar.tsx
  src/components/profileButton.tsx
  src/components/profileNav.tsx
  src/lib/jwt.ts
  src/lib/types/next-auth.d.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/login.ts
  src/pages/api/auth/signup.ts
  src/pages/tes.tsx
Labels: documentation, enhancement

#25 added chat tables
  prisma/migrations/20230613095021_added_chat_table/migration.sql
  prisma/schema.prisma
Labels: documentation

#26 Github Community Improvements
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-failing-test.md
  .github/ISSUE_TEMPLATE/3-docs-bug.md
  .github/ISSUE_TEMPLATE/4-feature-request.md
  .github/ISSUE_TEMPLATE/5-enhancement-request.md
  .github/ISSUE_TEMPLATE/6-security-report.md
  .github/ISSUE_TEMPLATE/7-question-support.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/config.yml
  .github/issue_label_bot.yaml
  .github/pull_request_template.md
  .github/settings.yml
Labels: documentation

#41 Backend Stuff
  package-lock.json
  package.json
  prisma/migrations/20230614092308_added_various_user_data/migration.sql
  prisma/migrations/20230614121549_fixed_users/migration.sql
  prisma/migrations/20230614123354_changed_default/migration.sql
  prisma/migrations/20230614133049_fi/migration.sql
  prisma/migrations/20230614133204_removed_role/migration.sql
  prisma/migrations/20230614133242_added/migration.sql
  prisma/migrations/20230614133518_added_default_role/migration.sql
  prisma/migrations/20230614134018_added_default_to_job/migration.sql
  prisma/migrations/20230618092637_added_many_tables/migration.sql
  prisma/migrations/20230618152204_remade_alamat/migration.sql
  prisma/migrations/20230618153358_fixed_alamat/migration.sql
  prisma/migrations/20230618180715_updated/migration.sql
  prisma/migrations/20230618180922_added_unique_flag_properti/migration.sql
  prisma/schema.prisma
  public/assets/profile/default.jpg
  public/assets/profile/private/aba9371d-5ee1-4ed4-b04e-613ab27e8072/avatar.jpg
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/design/route.ts
  src/app/api/designer/designer.ts
  src/app/api/login/route.ts
  src/app/api/property/[id]/route.ts
  src/app/api/property/route.ts
  src/app/api/property/upload/route.ts
  src/app/api/register/route.ts
  src/app/api/tukang/tukang.ts
  src/app/api/user/profile/route.ts
  src/app/api/user/route.ts
  src/components/chatButton.tsx
  src/components/navbar.tsx
  src/components/profileButton.tsx
  src/lib/axios.ts
  src/lib/jwt.ts
  src/lib/types/next-auth.d.ts
  src/pages/_app.tsx
  src/pages/api/profile/upload.ts
  src/pages/api/properti/image/upload.ts
  src/pages/checkApi.tsx
  src/pages/properti/[id].tsx
  src/pages/sellPropertyForm.tsx
  src/pages/settings.tsx
Labels: documentation, enhancement
